CREATE TABLE TB_FLATS
(
    FLAT_ID INT IDENTITY(1,1)
        CONSTRAINT PK_TB_FLATS
        PRIMARY KEY,

    TENANT_ID INT
        NOT NULL,

    TOWER_ID INT
        NOT NULL,

    FLAT_NO VARCHAR(50)
        NOT NULL,

    FLOOR_NO INT,

    AREA_SQFT DECIMAL(12,2),

    MAINTENANCE_RATE DECIMAL(12,2),

    STATUS VARCHAR(20)
        DEFAULT 'Vacant',

    CREATED_ON DATETIME
        DEFAULT GETDATE(),

    CONSTRAINT FK_TB_FLATS_TENANTS
        FOREIGN KEY (TENANT_ID)
        REFERENCES TB_TENANTS(TENANT_ID),

    CONSTRAINT FK_TB_FLATS_TOWERS
        FOREIGN KEY (TOWER_ID)
        REFERENCES TB_TOWERS(TOWER_ID)
);


ALTER TABLE TB_FLATS
ADD CONSTRAINT UQ_TB_FLATS
UNIQUE
(
    TENANT_ID,
    TOWER_ID,
    FLAT_NO
);