CREATE TABLE TB_TOWERS
(
    TOWER_ID INT IDENTITY(1,1)
        CONSTRAINT PK_TB_TOWERS
        PRIMARY KEY,

    TENANT_ID INT
        NOT NULL,

    TOWER_NAME VARCHAR(100)
        NOT NULL,

    TOTAL_FLOORS INT,

    STATUS VARCHAR(20)
        DEFAULT 'Active',

    CREATED_ON DATETIME
        DEFAULT GETDATE(),

    CONSTRAINT FK_TB_TOWERS_TENANTS
        FOREIGN KEY (TENANT_ID)
        REFERENCES TB_TENANTS(TENANT_ID)
);


ALTER TABLE TB_TOWERS
ADD CONSTRAINT UQ_TB_TOWERS
UNIQUE
(
    TENANT_ID,
    TOWER_NAME
);